apiVersion: v1
kind: ConfigMap
metadata:
  name: project-initdb-config
data:
  initdb.sql: |
      use project-service;
      CREATE TABLE banner
      (
          banner_id        BIGINT AUTO_INCREMENT NOT NULL,
          banner_image_url VARCHAR(255)          NOT NULL,
          banner_url       VARCHAR(255)          NOT NULL,
          CONSTRAINT pk_banner PRIMARY KEY (banner_id)
      );
      CREATE TABLE category
      (
          category_id   BIGINT AUTO_INCREMENT NOT NULL,
          category_name VARCHAR(255)          NOT NULL,
          CONSTRAINT pk_category PRIMARY KEY (category_id)
      );
      CREATE TABLE maker
      (
          maker_id           BIGINT AUTO_INCREMENT NOT NULL,
          created_at         datetime              NULL,
          updated_at         datetime              NULL,
          member_id          BIGINT                NOT NULL,
          maker_name         VARCHAR(255)          NOT NULL,
          maker_email        VARCHAR(255)          NOT NULL,
          maker_phone_number VARCHAR(255)          NOT NULL,
          maker_kakao_url    VARCHAR(255)          NULL,
          maker_home_url     VARCHAR(255)          NULL,
          maker_sns_url      VARCHAR(255)          NULL,
          CONSTRAINT pk_maker PRIMARY KEY (maker_id)
      );

      ALTER TABLE maker
          ADD CONSTRAINT uc_maker_member UNIQUE (member_id);
      CREATE TABLE project
      (
          project_id              BIGINT AUTO_INCREMENT          NOT NULL,
          created_at              datetime                       NULL,
          updated_at              datetime                       NULL,
          maker_id                BIGINT                         NULL,
          category_id             BIGINT                         NULL,
          project_name            VARCHAR(255)                   NOT NULL,
          project_description     VARCHAR(255)                   NOT NULL,
          project_tag             VARCHAR(255)                   NOT NULL,
          project_target_amount   BIGINT                         NOT NULL,
          project_status          VARCHAR(255) DEFAULT 'PENDING' NOT NULL,
          project_story_image_url VARCHAR(255)                   NOT NULL,
          project_is_authorized   BIT(1)                         NOT NULL,
          project_due_date        datetime                       NOT NULL,
          CONSTRAINT pk_project PRIMARY KEY (project_id)
      );

      ALTER TABLE project
          ADD CONSTRAINT FK_PROJECT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

      ALTER TABLE project
          ADD CONSTRAINT FK_PROJECT_ON_MAKER FOREIGN KEY (maker_id) REFERENCES maker (maker_id);

      CREATE TABLE project_image
      (
          project_image_id           BIGINT AUTO_INCREMENT NOT NULL,
          created_at                 datetime              NULL,
          updated_at                 datetime              NULL,
          project_id                 BIGINT                NULL,
          project_image_url          VARCHAR(255)          NOT NULL,
          project_image_is_thumbnail BIT(1)                NOT NULL,
          CONSTRAINT pk_project_image PRIMARY KEY (project_image_id)
      );

      ALTER TABLE project_image
          ADD CONSTRAINT FK_PROJECT_IMAGE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (project_id);

      CREATE TABLE lotdeal
      (
          lotdeal_id         BIGINT AUTO_INCREMENT NOT NULL,
          created_at         datetime              NULL,
          updated_at         datetime              NULL,
          project_id         BIGINT                NULL,
          lotdeal_start_time datetime              NULL,
          lotdeal_due_time   datetime              NULL,
          CONSTRAINT pk_lotdeal PRIMARY KEY (lotdeal_id)
      );

      ALTER TABLE lotdeal
          ADD CONSTRAINT FK_LOTDEAL_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (project_id);

      CREATE TABLE product
      (
          product_id                        BIGINT AUTO_INCREMENT NOT NULL,
          created_at                        datetime              NULL,
          updated_at                        datetime              NULL,
          project_id                        BIGINT                NULL,
          product_name                      VARCHAR(255)          NOT NULL,
          product_description               VARCHAR(255)          NOT NULL,
          product_price                     BIGINT                NOT NULL,
          product_registered_stock_quantity BIGINT                NOT NULL,
          product_current_stock_quantity    BIGINT                NOT NULL,
          CONSTRAINT pk_product PRIMARY KEY (product_id)
      );

      ALTER TABLE product
          ADD CONSTRAINT FK_PRODUCT_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (project_id);
      
      CREATE TABLE support_signature
      (
          support_signature_id      BIGINT AUTO_INCREMENT NOT NULL,
          created_at                datetime              NULL,
          updated_at                datetime              NULL,
          project_id                BIGINT                NULL,
          member_id                 BIGINT                NOT NULL,
          support_signature_content VARCHAR(500)          NOT NULL,
          CONSTRAINT pk_support_signature PRIMARY KEY (support_signature_id)
      );

      ALTER TABLE support_signature
          ADD CONSTRAINT FK_SUPPORT_SIGNATURE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (project_id);