apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: admin-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: admin-pod
      # Set pod's label
      labels:
        app: admin-service
        profile: dev
    spec:
      containers:
        - name: admin-service
          image: akak640/lotdiz-admin-service
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.34
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: admin-service
          volumeMounts:
            - name: admin-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: admin-initdb
          configMap:
            name: admin-initdb-config