apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: admin-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: admin-pod
      # Set pod's label
      labels:
        app: admin-service
        profile: dev
    spec:
      containers:
        - name: admin-service
          image: akak640/lotdiz-admin-service
