apiVersion: v1
kind: ConfigMap
metadata:
  name: member-initdb-config
data:
  initdb.sql: |
    use member-service;
    CREATE TABLE member
    (
        member_id                BIGINT AUTO_INCREMENT NOT NULL,
        created_at               datetime              NULL,
        updated_at               datetime              NULL,
        member_role              VARCHAR(255)          NOT NULL,
        member_email             VARCHAR(255)          NOT NULL,
        member_password          VARCHAR(255)          NOT NULL,
        member_name              VARCHAR(10)           NOT NULL,
        member_phone_number      VARCHAR(255)          NOT NULL,
        member_point             BIGINT                NOT NULL,
        member_profile_image_url VARCHAR(255)          NOT NULL,
        member_privacy_agreement BIT(1)                NOT NULL,
        CONSTRAINT pk_member PRIMARY KEY (member_id)
    );

    ALTER TABLE member
        ADD CONSTRAINT uc_member_member_email UNIQUE (member_email);

    CREATE TABLE likes
    (
        created_at datetime NULL,
        member_id  BIGINT   NOT NULL,
        project_id BIGINT   NOT NULL,
        CONSTRAINT pk_likes PRIMARY KEY (member_id, project_id)
    );

    ALTER TABLE likes
        ADD CONSTRAINT FK_LIKES_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);
    
    CREATE TABLE delivery_address
    (
        delivery_address_id                     BIGINT       NOT NULL,
        created_at                              datetime     NULL,
        updated_at                              datetime     NULL,
        delivery_address_recipient_name         VARCHAR(255) NOT NULL,
        delivery_address_recipient_phone_number VARCHAR(255) NOT NULL,
        delivery_address_recipient_email        VARCHAR(255) NULL,
        delivery_address_request                VARCHAR(255) NULL,
        delivery_address_road_name              VARCHAR(255) NOT NULL,
        delivery_address_detail                 VARCHAR(255) NOT NULL,
        delivery_address_zip_code               VARCHAR(255) NOT NULL,
        delivery_address_is_default             BIT(1)       NOT NULL,
        member_id                               BIGINT       NULL,
        CONSTRAINT pk_deliveryaddress PRIMARY KEY (delivery_address_id)
    );

    ALTER TABLE delivery_address
        ADD CONSTRAINT FK_DELIVERYADDRESS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

    CREATE TABLE membership_policy
    (
        membership_policy_id                      BIGINT AUTO_INCREMENT NOT NULL,
        created_at                                datetime              NULL,
        updated_at                                datetime              NULL,
        membership_policy_grade                   VARCHAR(255)          NOT NULL,
        membership_policy_subscription_fee        BIGINT                NOT NULL,
        membership_policy_discount_rate           INT                   NOT NULL,
        membership_policy_point_accumulation_rate INT                   NOT NULL,
        CONSTRAINT pk_membershippolicy PRIMARY KEY (membership_policy_id)
    );

    CREATE TABLE membership
    (
        membership_id                      BIGINT AUTO_INCREMENT NOT NULL,
        membership_subscription_created_at datetime              NULL,
        membership_subscription_expired_at datetime              NULL,
        membership_status                  BIT(1)                NULL,
        membership_policy_id               BIGINT                NOT NULL,
        membership_subscription_id         BIGINT                NULL,
        member_id                          BIGINT                NULL,
        CONSTRAINT pk_membership PRIMARY KEY (membership_id)
    );

    ALTER TABLE membership
        ADD CONSTRAINT FK_MEMBERSHIP_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

    ALTER TABLE membership
        ADD CONSTRAINT FK_MEMBERSHIP_ON_MEMBERSHIP_POLICY FOREIGN KEY (membership_policy_id) REFERENCES membership_policy (membership_policy_id);

    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_USER',now(),now(),'test1@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '최소영', '01033334444', 100, 'https://picsum.photos/200', true);
    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_USER',now(),now(),'test2@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '이채민', '01011112222', 500, 'https://picsum.photos/200', true);
    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_USER',now(),now(),'test3@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '이상원', '01055556666', 700, 'https://picsum.photos/200', true);
    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_USER',now(),now(),'test4@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '이진우', '01033376666', 1000, 'https://picsum.photos/200', true);
    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_USER',now(),now(),'test5@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '이우엽', '01033344333', 5000, 'https://picsum.photos/200', true);
    INSERT INTO member(member_role, created_at, updated_at, member_email, member_password, member_name, member_phone_number, member_point, member_profile_image_url, member_privacy_agreement) VALUES('ROLE_ADMIN',now(),now(),'admin123@naver.com','$2a$12$1KExfMQ7nNPKSrJh4O2a/u60QCW/.W5PqF9d7KwFzDV8hWbuxHU8W', '관리자', '01000000000', 5000, 'https://picsum.photos/200', true);

    INSERT INTO membership_policy(membership_policy_grade, membership_policy_subscription_fee, membership_policy_discount_rate, membership_policy_point_accumulation_rate) VALUES('펀딩프렌즈', 6900, 3, 1);
    INSERT INTO membership_policy(membership_policy_grade, membership_policy_subscription_fee, membership_policy_discount_rate, membership_policy_point_accumulation_rate) VALUES('펀딩파트너', 9900, 5, 2);