apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  labels:
    app: delivery-deployment
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: delivery-service
  replicas: 2
  # Pod Spec
  template:
    metadata:
      name: delivery-service
      # Set pod's label
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: akak640/delivery-service
